files:
  include: 'src/**/*.s+(a|c)ss'
options:
  formatter: stylish
rules:
  attribute-quotes: 1
  bem-depth: 2
  brace-style: 1
  border-zero: 2
  class-name-format: 2
  clean-import-paths: 0
  declarations-before-nesting: 0
  empty-args: 0
  empty-line-between-blocks: 1
  extends-before-declarations: 0
  extends-before-mixins: 0
  final-newline: 2
  force-attribute-nesting: 0
  force-element-nesting: 2
  force-pseudo-nesting: 2
  function-name-format: 2
  hex-length: 1
  hex-notation: 1
  id-name-format: 0
  indentation: 1
  leading-zero: 1
  max-file-line-count: 2
  mixin-name-format: 1
  mixins-before-declarations: 0
  nesting-depth: 2
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 2
  no-color-literals: 2
  no-combinators: 0
  no-css-comments: 0
  no-debug: 2
  no-disallowed-properties: 0
  no-duplicate-properties: 2
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements: 0
  no-trailing-whitespace: 1
  no-trailing-zero: 1
  no-transition-all: 2
  no-universal-selectors: 1
  no-url-domains: 2
  no-url-protocols: 2
  no-vendor-prefixes: 2
  no-warn: 2
  one-declaration-per-line: 1
  placeholder-in-extend: 2
  placeholder-name-format: 1
  property-sort-order: 1
  property-units: 1
  pseudo-element: 1
  shorthand-values: 1
  single-line-per-selector: 1
  space-after-bang: 1
  space-after-colon: 1
  space-after-comma: 1
  space-around-operator: 1
  space-before-bang: 1
  space-before-brace: 1
  space-before-colon: 1
  space-between-parens: 1
  trailing-semicolon: 2
  url-quotes: 2
  variable-for-property: 0
  variable-name-format: 1
  quotes: 1
  zero-unit: 1
